# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 167e80be4eb53be7a56f876a7d806f9477e0ba8bf02c98cc95da7b8481ca0fcc533e53314773af1a1fc044ffba91ce949070accd6f5dcbbb7dc9230996da9e68

test:
  secret_key_base: 56e5987758121d8850dd6c26002b4bedf17cd8f71443697eba47e9583987e36dfd671ff81983fd47306df00b95f3671abc53d6dd809b245f5d16cf9abb48240c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
